package GraficadorTercerParcial;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author marisol
 */
public class Menu extends javax.swing.JFrame {
    int figura,lineas,lineasF;
    String textura,tpoligono,tfigura,poligono;
    Color cT,cP,cF;
    Icon icono;
    ImageIcon icon;
    File f;
    /**
     * Creates new form Menu1
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngFig = new javax.swing.ButtonGroup();
        btngPol = new javax.swing.ButtonGroup();
        btngText = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnImg = new javax.swing.JButton();
        btnGraf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        lblText = new javax.swing.JLabel();
        lblPol = new javax.swing.JLabel();
        lblFig = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnDiag = new javax.swing.JRadioButton();
        rbtnEstr = new javax.swing.JRadioButton();
        rbtnCont = new javax.swing.JRadioButton();
        rbtnSol = new javax.swing.JRadioButton();
        rbtnCirc = new javax.swing.JRadioButton();
        rbtnCuad = new javax.swing.JRadioButton();
        btnText = new javax.swing.JButton();
        btnPol = new javax.swing.JButton();
        btnFig = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cImg = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        lblImg.setMaximumSize(new java.awt.Dimension(200, 200));
        lblImg.setMinimumSize(new java.awt.Dimension(200, 200));
        lblImg.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnImg.setText("Imagen de Fondo");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        btnGraf.setText("Graficar");
        btnGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Número a graficar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Polígono a graficar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Número a graficar");

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jSlider2.setMaximum(10);
        jSlider2.setValue(3);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        lblText.setText("50");

        lblPol.setText("Hexágono");

        lblFig.setText("50");

        jLabel7.setText("Textura");

        jLabel8.setText("Tipos de polígonos");

        jLabel9.setText("Tipos de figuras");

        btngText.add(rbtnDiag);
        rbtnDiag.setText("Diagonales");
        rbtnDiag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnDiag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnDiag.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnDiag.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btngText.add(rbtnEstr);
        rbtnEstr.setText("Estrella");
        rbtnEstr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnEstr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnEstr.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnEstr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btngPol.add(rbtnCont);
        rbtnCont.setText("Contorno");
        rbtnCont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnCont.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnCont.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnCont.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btngPol.add(rbtnSol);
        rbtnSol.setText("Solido");
        rbtnSol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnSol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnSol.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnSol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btngFig.add(rbtnCirc);
        rbtnCirc.setText("Circulos");
        rbtnCirc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnCirc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnCirc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnCirc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btngFig.add(rbtnCuad);
        rbtnCuad.setText("Cuadrados");
        rbtnCuad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnCuad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnCuad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnCuad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnText.setText("Color de textura");
        btnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextActionPerformed(evt);
            }
        });

        btnPol.setText("Color de polígono");
        btnPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolActionPerformed(evt);
            }
        });

        btnFig.setText("Color de figuras");
        btnFig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jMenu1.setText("Archivo");

        cImg.setText("Cambiar Imagen");
        cImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cImgActionPerformed(evt);
            }
        });
        jMenu1.add(cImg);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        acerca.setText("Acerca de...");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        jMenu2.add(acerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rbtnDiag)
                .addGap(46, 46, 46)
                .addComponent(rbtnEstr)
                .addGap(43, 43, 43)
                .addComponent(rbtnCont)
                .addGap(18, 18, 18)
                .addComponent(rbtnSol))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(lblText))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btnText))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(26, 26, 26)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnPol)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblPol)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(btnFig))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtnCirc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                    .addComponent(rbtnCuad)
                                    .addGap(20, 20, 20))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(lblFig)
                            .addContainerGap())))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGraf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImg))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblText)
                                    .addComponent(lblFig)
                                    .addComponent(lblPol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnCirc)
                                            .addComponent(rbtnCuad)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbtnSol)
                                                    .addComponent(rbtnCont)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbtnDiag)
                                                    .addComponent(rbtnEstr))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnText)
                                    .addComponent(btnPol)
                                    .addComponent(btnFig))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGraf))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG & GIF & BMP", "jpg", "gif", "bmp");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();
            icon = new ImageIcon(f.toString());
            icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
            lblImg.setIcon(icono);
        }
    }//GEN-LAST:event_btnImgActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        lineas=jSlider1.getValue();
        String valor = lineas+"";
        lblText.setText(valor);       
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        String opc = String.valueOf(jSlider2.getValue());
        switch(opc){
            case "3" -> {
                lblPol.setText("Triangulo");
                poligono="Triangulo";
            }
            case "4" -> {
                lblPol.setText("Cuadrado");
                poligono="Cuadrado";
            }
            case "5" -> {
                lblPol.setText("Pentágono");
                poligono="Pentágono";
            }
            case "6" -> {
                lblPol.setText("Hexágono");
                poligono="Hexágono";
            }
            case "7" -> {
                lblPol.setText("Heptágono");
                poligono="Heptágono";
            }
            case "8" -> {
                lblPol.setText("Octágono");
                poligono="Octágono";
            }
            case "9" -> {
                lblPol.setText("Eneágono");
                poligono="Eneágono";
            }
            case "10" -> {
                lblPol.setText("Decágono");
                poligono="Decágono";
            }
        }

        
    }//GEN-LAST:event_jSlider2StateChanged

    private void cImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG & GIF & BMP", "jpg", "gif", "bmp");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();
            icon = new ImageIcon(f.toString());
            icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
            lblImg.setIcon(icono);
        }
    }//GEN-LAST:event_cImgActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Graficación por Computadora"+"\n"+"Marisol Benítez Durán"+"\n"+"8°A T/M","Alumno: ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaActionPerformed

    private void btnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextActionPerformed
        // TODO add your handling code here:
        cT = JColorChooser.showDialog(rootPane, "Selecciona un color", Color.WHITE);
        btnText.setBackground(cT);
        repaint();
    }//GEN-LAST:event_btnTextActionPerformed

    private void btnPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolActionPerformed
        // TODO add your handling code here:
        cP = JColorChooser.showDialog(rootPane, "Selecciona un color", Color.WHITE);
        btnPol.setBackground(cP);
        repaint();
    }//GEN-LAST:event_btnPolActionPerformed

    private void btnFigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigActionPerformed
        // TODO add your handling code here:
        cF = JColorChooser.showDialog(rootPane, "Selecciona un color", Color.WHITE);
        btnFig.setBackground(cF);
        repaint();
    }//GEN-LAST:event_btnFigActionPerformed

    private void btnGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafActionPerformed
        // TODO add your handling code here:
        if(rbtnDiag.isSelected()){
            textura = "Diagonales";
        }
        if(rbtnEstr.isSelected()){
            textura = "Estrella";
        }
        if(rbtnCont.isSelected()){
            tpoligono = "Contorno";
        }
        if(rbtnSol.isSelected()){
            tpoligono = "Solido";
        }
        if(rbtnCirc.isSelected()){
            tfigura = "Circulos";
        }
        if(rbtnCuad.isSelected()){
            tfigura = "Cuadrados";
        }
        
        if(lineas == 0)
        {
            lineas = 50;
        }   
        if(poligono == null)
        {
            poligono = "Hexágono";
        }
        if(lineasF == 0){
            lineasF = 50;
        }
        if(textura == null && tpoligono == null && tfigura == null)
        {
            JOptionPane.showMessageDialog(rootPane, "Seleccione las opciones para el tipo de dibujado");
        }else{
            Graficador g = new Graficador(lineas,lineasF,textura,tpoligono,tfigura,poligono,cT,cF,cP,figura,icono,icon,f);
            g.setVisible(true); 
        }
        
    }//GEN-LAST:event_btnGrafActionPerformed

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        // TODO add your handling code here:
        lineasF=jSlider3.getValue();
        String valorF = lineasF+"";
        lblFig.setText(valorF);    
    }//GEN-LAST:event_jSlider3StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acerca;
    private javax.swing.JButton btnFig;
    private javax.swing.JButton btnGraf;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnPol;
    private javax.swing.JButton btnText;
    private javax.swing.ButtonGroup btngFig;
    private javax.swing.ButtonGroup btngPol;
    private javax.swing.ButtonGroup btngText;
    private javax.swing.JMenuItem cImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JLabel lblFig;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblText;
    private javax.swing.JRadioButton rbtnCirc;
    private javax.swing.JRadioButton rbtnCont;
    private javax.swing.JRadioButton rbtnCuad;
    private javax.swing.JRadioButton rbtnDiag;
    private javax.swing.JRadioButton rbtnEstr;
    private javax.swing.JRadioButton rbtnSol;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
