/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package battleship;

/**
 *
 * @author Ferna
 */
public class Mar extends javax.swing.JFrame {

    /**
     * Creates new form Mar
     */
    public Mar() {
        initComponents();
        lblA4.setBounds(100, 100, 60, 60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblA1 = new javax.swing.JLabel();
        lblBoardTopNumbers = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        lblA6 = new javax.swing.JLabel();
        lblA7 = new javax.swing.JLabel();
        lblA8 = new javax.swing.JLabel();
        lblA9 = new javax.swing.JLabel();
        lblA10 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblB4 = new javax.swing.JLabel();
        lblB5 = new javax.swing.JLabel();
        lblB6 = new javax.swing.JLabel();
        lblB7 = new javax.swing.JLabel();
        lblB8 = new javax.swing.JLabel();
        lblB9 = new javax.swing.JLabel();
        lblB10 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();
        lblC6 = new javax.swing.JLabel();
        lblC7 = new javax.swing.JLabel();
        lblC8 = new javax.swing.JLabel();
        lblC9 = new javax.swing.JLabel();
        lblC10 = new javax.swing.JLabel();
        lblSD1 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lblSD2 = new javax.swing.JLabel();
        lblSD3 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lblSE1 = new javax.swing.JLabel();
        lblSE2 = new javax.swing.JLabel();
        lblSE3 = new javax.swing.JLabel();
        lblSE4 = new javax.swing.JLabel();
        lblSE5 = new javax.swing.JLabel();
        lblSE6 = new javax.swing.JLabel();
        lblSE7 = new javax.swing.JLabel();
        lblSE8 = new javax.swing.JLabel();
        lblSE9 = new javax.swing.JLabel();
        lblSE10 = new javax.swing.JLabel();
        lblSF1 = new javax.swing.JLabel();
        lblSF2 = new javax.swing.JLabel();
        lblSF3 = new javax.swing.JLabel();
        lblSF4 = new javax.swing.JLabel();
        lblSF5 = new javax.swing.JLabel();
        lblSF6 = new javax.swing.JLabel();
        lblSF7 = new javax.swing.JLabel();
        lblSF8 = new javax.swing.JLabel();
        lblSF9 = new javax.swing.JLabel();
        lblSF10 = new javax.swing.JLabel();
        lblSG1 = new javax.swing.JLabel();
        lblSG4 = new javax.swing.JLabel();
        lblSG2 = new javax.swing.JLabel();
        lblSG3 = new javax.swing.JLabel();
        lblSG5 = new javax.swing.JLabel();
        lblSG6 = new javax.swing.JLabel();
        lblSG7 = new javax.swing.JLabel();
        lblSG8 = new javax.swing.JLabel();
        lblSG9 = new javax.swing.JLabel();
        lblSG10 = new javax.swing.JLabel();
        lblSH1 = new javax.swing.JLabel();
        lblSH2 = new javax.swing.JLabel();
        lblSH3 = new javax.swing.JLabel();
        lblSH4 = new javax.swing.JLabel();
        lblSH5 = new javax.swing.JLabel();
        lblSH6 = new javax.swing.JLabel();
        lblSH7 = new javax.swing.JLabel();
        lblSH8 = new javax.swing.JLabel();
        lblSH9 = new javax.swing.JLabel();
        lblSH10 = new javax.swing.JLabel();
        lblSI1 = new javax.swing.JLabel();
        lblSI2 = new javax.swing.JLabel();
        lblSI3 = new javax.swing.JLabel();
        lblSI4 = new javax.swing.JLabel();
        lblSI5 = new javax.swing.JLabel();
        lblSI6 = new javax.swing.JLabel();
        lblSI7 = new javax.swing.JLabel();
        lblSI8 = new javax.swing.JLabel();
        lblSI9 = new javax.swing.JLabel();
        lblIS10 = new javax.swing.JLabel();
        lblSJ1 = new javax.swing.JLabel();
        lblSJ2 = new javax.swing.JLabel();
        lblSJ3 = new javax.swing.JLabel();
        lblSJ4 = new javax.swing.JLabel();
        lblSJ5 = new javax.swing.JLabel();
        lblSJ6 = new javax.swing.JLabel();
        lblSJ7 = new javax.swing.JLabel();
        lblSJ8 = new javax.swing.JLabel();
        lblSJ9 = new javax.swing.JLabel();
        lblSJ10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBoardSideA = new javax.swing.JLabel();
        lblBoardSideB = new javax.swing.JLabel();
        lblBoardSideC = new javax.swing.JLabel();
        lblBoardSideD = new javax.swing.JLabel();
        lblBoardSideE = new javax.swing.JLabel();
        lblBoardSideF = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1300, 900));
        setMinimumSize(new java.awt.Dimension(1300, 900));
        getContentPane().setLayout(null);

        lblA1.setBackground(new java.awt.Color(255, 255, 255));
        lblA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA1.setOpaque(true);
        getContentPane().add(lblA1);
        lblA1.setBounds(40, 50, 60, 60);

        lblBoardTopNumbers.setText("1                  2                 3                  4                   5                6                   7                   8                 9                 10");
        getContentPane().add(lblBoardTopNumbers);
        lblBoardTopNumbers.setBounds(70, 20, 600, 16);

        lblA4.setBackground(new java.awt.Color(255, 255, 255));
        lblA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA4.setOpaque(true);
        getContentPane().add(lblA4);
        lblA4.setBounds(220, 50, 60, 60);

        lblA2.setBackground(new java.awt.Color(255, 255, 255));
        lblA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA2.setOpaque(true);
        getContentPane().add(lblA2);
        lblA2.setBounds(100, 50, 60, 60);

        lblA3.setBackground(new java.awt.Color(255, 255, 255));
        lblA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA3.setOpaque(true);
        getContentPane().add(lblA3);
        lblA3.setBounds(160, 50, 60, 60);

        lblA5.setBackground(new java.awt.Color(255, 255, 255));
        lblA5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA5.setOpaque(true);
        getContentPane().add(lblA5);
        lblA5.setBounds(280, 50, 60, 60);

        lblA6.setBackground(new java.awt.Color(255, 255, 255));
        lblA6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA6.setOpaque(true);
        getContentPane().add(lblA6);
        lblA6.setBounds(340, 50, 60, 60);

        lblA7.setBackground(new java.awt.Color(255, 255, 255));
        lblA7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA7.setOpaque(true);
        getContentPane().add(lblA7);
        lblA7.setBounds(400, 50, 60, 60);

        lblA8.setBackground(new java.awt.Color(255, 255, 255));
        lblA8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA8.setOpaque(true);
        getContentPane().add(lblA8);
        lblA8.setBounds(460, 50, 60, 60);

        lblA9.setBackground(new java.awt.Color(255, 255, 255));
        lblA9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA9.setOpaque(true);
        getContentPane().add(lblA9);
        lblA9.setBounds(520, 50, 60, 60);

        lblA10.setBackground(new java.awt.Color(255, 255, 255));
        lblA10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblA10.setOpaque(true);
        getContentPane().add(lblA10);
        lblA10.setBounds(580, 50, 60, 60);

        lblB1.setBackground(new java.awt.Color(255, 255, 255));
        lblB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB1.setOpaque(true);
        getContentPane().add(lblB1);
        lblB1.setBounds(40, 110, 60, 60);

        lblB2.setBackground(new java.awt.Color(255, 255, 255));
        lblB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB2.setOpaque(true);
        getContentPane().add(lblB2);
        lblB2.setBounds(100, 110, 60, 60);

        lblB3.setBackground(new java.awt.Color(255, 255, 255));
        lblB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB3.setOpaque(true);
        getContentPane().add(lblB3);
        lblB3.setBounds(160, 110, 60, 60);

        lblB4.setBackground(new java.awt.Color(255, 255, 255));
        lblB4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB4.setOpaque(true);
        getContentPane().add(lblB4);
        lblB4.setBounds(220, 110, 60, 60);

        lblB5.setBackground(new java.awt.Color(255, 255, 255));
        lblB5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB5.setOpaque(true);
        getContentPane().add(lblB5);
        lblB5.setBounds(280, 110, 60, 60);

        lblB6.setBackground(new java.awt.Color(255, 255, 255));
        lblB6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB6.setOpaque(true);
        getContentPane().add(lblB6);
        lblB6.setBounds(340, 110, 60, 60);

        lblB7.setBackground(new java.awt.Color(255, 255, 255));
        lblB7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB7.setOpaque(true);
        getContentPane().add(lblB7);
        lblB7.setBounds(400, 110, 60, 60);

        lblB8.setBackground(new java.awt.Color(255, 255, 255));
        lblB8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB8.setOpaque(true);
        getContentPane().add(lblB8);
        lblB8.setBounds(460, 110, 60, 60);

        lblB9.setBackground(new java.awt.Color(255, 255, 255));
        lblB9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB9.setOpaque(true);
        getContentPane().add(lblB9);
        lblB9.setBounds(520, 110, 60, 60);

        lblB10.setBackground(new java.awt.Color(255, 255, 255));
        lblB10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblB10.setOpaque(true);
        getContentPane().add(lblB10);
        lblB10.setBounds(580, 110, 60, 60);

        lblC1.setBackground(new java.awt.Color(255, 255, 255));
        lblC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC1.setOpaque(true);
        getContentPane().add(lblC1);
        lblC1.setBounds(40, 170, 60, 60);

        lblC2.setBackground(new java.awt.Color(255, 255, 255));
        lblC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC2.setOpaque(true);
        getContentPane().add(lblC2);
        lblC2.setBounds(100, 170, 60, 60);

        lblC3.setBackground(new java.awt.Color(255, 255, 255));
        lblC3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC3.setOpaque(true);
        getContentPane().add(lblC3);
        lblC3.setBounds(160, 170, 60, 60);

        lblC4.setBackground(new java.awt.Color(255, 255, 255));
        lblC4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC4.setOpaque(true);
        getContentPane().add(lblC4);
        lblC4.setBounds(220, 170, 60, 60);

        lblC5.setBackground(new java.awt.Color(255, 255, 255));
        lblC5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC5.setOpaque(true);
        getContentPane().add(lblC5);
        lblC5.setBounds(280, 170, 60, 60);

        lblC6.setBackground(new java.awt.Color(255, 255, 255));
        lblC6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC6.setOpaque(true);
        getContentPane().add(lblC6);
        lblC6.setBounds(340, 170, 60, 60);

        lblC7.setBackground(new java.awt.Color(255, 255, 255));
        lblC7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC7.setOpaque(true);
        getContentPane().add(lblC7);
        lblC7.setBounds(400, 170, 60, 60);

        lblC8.setBackground(new java.awt.Color(255, 255, 255));
        lblC8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC8.setOpaque(true);
        getContentPane().add(lblC8);
        lblC8.setBounds(460, 170, 60, 60);

        lblC9.setBackground(new java.awt.Color(255, 255, 255));
        lblC9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC9.setOpaque(true);
        getContentPane().add(lblC9);
        lblC9.setBounds(520, 170, 60, 60);

        lblC10.setBackground(new java.awt.Color(255, 255, 255));
        lblC10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblC10.setOpaque(true);
        getContentPane().add(lblC10);
        lblC10.setBounds(580, 170, 60, 60);

        lblSD1.setBackground(new java.awt.Color(255, 255, 255));
        lblSD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSD1.setOpaque(true);
        getContentPane().add(lblSD1);
        lblSD1.setBounds(40, 230, 60, 60);

        lbl28.setBackground(new java.awt.Color(255, 255, 255));
        lbl28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl28.setOpaque(true);
        getContentPane().add(lbl28);
        lbl28.setBounds(220, 230, 60, 60);

        lblSD2.setBackground(new java.awt.Color(255, 255, 255));
        lblSD2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSD2.setOpaque(true);
        getContentPane().add(lblSD2);
        lblSD2.setBounds(100, 230, 60, 60);

        lblSD3.setBackground(new java.awt.Color(255, 255, 255));
        lblSD3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSD3.setOpaque(true);
        getContentPane().add(lblSD3);
        lblSD3.setBounds(160, 230, 60, 60);

        lbl31.setBackground(new java.awt.Color(255, 255, 255));
        lbl31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl31.setOpaque(true);
        getContentPane().add(lbl31);
        lbl31.setBounds(280, 230, 60, 60);

        lbl32.setBackground(new java.awt.Color(255, 255, 255));
        lbl32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl32.setOpaque(true);
        getContentPane().add(lbl32);
        lbl32.setBounds(340, 230, 60, 60);

        lbl33.setBackground(new java.awt.Color(255, 255, 255));
        lbl33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl33.setOpaque(true);
        getContentPane().add(lbl33);
        lbl33.setBounds(400, 230, 60, 60);

        lbl34.setBackground(new java.awt.Color(255, 255, 255));
        lbl34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl34.setOpaque(true);
        getContentPane().add(lbl34);
        lbl34.setBounds(460, 230, 60, 60);

        lbl35.setBackground(new java.awt.Color(255, 255, 255));
        lbl35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl35.setOpaque(true);
        getContentPane().add(lbl35);
        lbl35.setBounds(520, 230, 60, 60);

        lbl36.setBackground(new java.awt.Color(255, 255, 255));
        lbl36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl36.setOpaque(true);
        getContentPane().add(lbl36);
        lbl36.setBounds(580, 230, 60, 60);

        lblSE1.setBackground(new java.awt.Color(255, 255, 255));
        lblSE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE1.setOpaque(true);
        getContentPane().add(lblSE1);
        lblSE1.setBounds(40, 290, 60, 60);

        lblSE2.setBackground(new java.awt.Color(255, 255, 255));
        lblSE2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE2.setOpaque(true);
        getContentPane().add(lblSE2);
        lblSE2.setBounds(100, 290, 60, 60);

        lblSE3.setBackground(new java.awt.Color(255, 255, 255));
        lblSE3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE3.setOpaque(true);
        getContentPane().add(lblSE3);
        lblSE3.setBounds(160, 290, 60, 60);

        lblSE4.setBackground(new java.awt.Color(255, 255, 255));
        lblSE4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE4.setOpaque(true);
        getContentPane().add(lblSE4);
        lblSE4.setBounds(220, 290, 60, 60);

        lblSE5.setBackground(new java.awt.Color(255, 255, 255));
        lblSE5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE5.setOpaque(true);
        getContentPane().add(lblSE5);
        lblSE5.setBounds(280, 290, 60, 60);

        lblSE6.setBackground(new java.awt.Color(255, 255, 255));
        lblSE6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE6.setOpaque(true);
        getContentPane().add(lblSE6);
        lblSE6.setBounds(340, 290, 60, 60);

        lblSE7.setBackground(new java.awt.Color(255, 255, 255));
        lblSE7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE7.setOpaque(true);
        getContentPane().add(lblSE7);
        lblSE7.setBounds(400, 290, 60, 60);

        lblSE8.setBackground(new java.awt.Color(255, 255, 255));
        lblSE8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE8.setOpaque(true);
        getContentPane().add(lblSE8);
        lblSE8.setBounds(460, 290, 60, 60);

        lblSE9.setBackground(new java.awt.Color(255, 255, 255));
        lblSE9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE9.setOpaque(true);
        getContentPane().add(lblSE9);
        lblSE9.setBounds(520, 290, 60, 60);

        lblSE10.setBackground(new java.awt.Color(255, 255, 255));
        lblSE10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSE10.setOpaque(true);
        getContentPane().add(lblSE10);
        lblSE10.setBounds(580, 290, 60, 60);

        lblSF1.setBackground(new java.awt.Color(255, 255, 255));
        lblSF1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF1.setOpaque(true);
        getContentPane().add(lblSF1);
        lblSF1.setBounds(40, 350, 60, 60);

        lblSF2.setBackground(new java.awt.Color(255, 255, 255));
        lblSF2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF2.setOpaque(true);
        getContentPane().add(lblSF2);
        lblSF2.setBounds(100, 350, 60, 60);

        lblSF3.setBackground(new java.awt.Color(255, 255, 255));
        lblSF3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF3.setOpaque(true);
        getContentPane().add(lblSF3);
        lblSF3.setBounds(160, 350, 60, 60);

        lblSF4.setBackground(new java.awt.Color(255, 255, 255));
        lblSF4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF4.setOpaque(true);
        getContentPane().add(lblSF4);
        lblSF4.setBounds(220, 350, 60, 60);

        lblSF5.setBackground(new java.awt.Color(255, 255, 255));
        lblSF5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF5.setOpaque(true);
        getContentPane().add(lblSF5);
        lblSF5.setBounds(280, 350, 60, 60);

        lblSF6.setBackground(new java.awt.Color(255, 255, 255));
        lblSF6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF6.setOpaque(true);
        getContentPane().add(lblSF6);
        lblSF6.setBounds(340, 350, 60, 60);

        lblSF7.setBackground(new java.awt.Color(255, 255, 255));
        lblSF7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF7.setOpaque(true);
        getContentPane().add(lblSF7);
        lblSF7.setBounds(400, 350, 60, 60);

        lblSF8.setBackground(new java.awt.Color(255, 255, 255));
        lblSF8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF8.setOpaque(true);
        getContentPane().add(lblSF8);
        lblSF8.setBounds(460, 350, 60, 60);

        lblSF9.setBackground(new java.awt.Color(255, 255, 255));
        lblSF9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF9.setOpaque(true);
        getContentPane().add(lblSF9);
        lblSF9.setBounds(520, 350, 60, 60);

        lblSF10.setBackground(new java.awt.Color(255, 255, 255));
        lblSF10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSF10.setOpaque(true);
        getContentPane().add(lblSF10);
        lblSF10.setBounds(580, 350, 60, 60);

        lblSG1.setBackground(new java.awt.Color(255, 255, 255));
        lblSG1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG1.setOpaque(true);
        getContentPane().add(lblSG1);
        lblSG1.setBounds(40, 410, 60, 60);

        lblSG4.setBackground(new java.awt.Color(255, 255, 255));
        lblSG4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG4.setOpaque(true);
        getContentPane().add(lblSG4);
        lblSG4.setBounds(220, 410, 60, 60);

        lblSG2.setBackground(new java.awt.Color(255, 255, 255));
        lblSG2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG2.setOpaque(true);
        getContentPane().add(lblSG2);
        lblSG2.setBounds(100, 410, 60, 60);

        lblSG3.setBackground(new java.awt.Color(255, 255, 255));
        lblSG3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG3.setOpaque(true);
        getContentPane().add(lblSG3);
        lblSG3.setBounds(160, 410, 60, 60);

        lblSG5.setBackground(new java.awt.Color(255, 255, 255));
        lblSG5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG5.setOpaque(true);
        getContentPane().add(lblSG5);
        lblSG5.setBounds(280, 410, 60, 60);

        lblSG6.setBackground(new java.awt.Color(255, 255, 255));
        lblSG6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG6.setOpaque(true);
        getContentPane().add(lblSG6);
        lblSG6.setBounds(340, 410, 60, 60);

        lblSG7.setBackground(new java.awt.Color(255, 255, 255));
        lblSG7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG7.setOpaque(true);
        getContentPane().add(lblSG7);
        lblSG7.setBounds(400, 410, 60, 60);

        lblSG8.setBackground(new java.awt.Color(255, 255, 255));
        lblSG8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG8.setOpaque(true);
        getContentPane().add(lblSG8);
        lblSG8.setBounds(460, 410, 60, 60);

        lblSG9.setBackground(new java.awt.Color(255, 255, 255));
        lblSG9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG9.setOpaque(true);
        getContentPane().add(lblSG9);
        lblSG9.setBounds(520, 410, 60, 60);

        lblSG10.setBackground(new java.awt.Color(255, 255, 255));
        lblSG10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSG10.setOpaque(true);
        getContentPane().add(lblSG10);
        lblSG10.setBounds(580, 410, 60, 60);

        lblSH1.setBackground(new java.awt.Color(255, 255, 255));
        lblSH1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH1.setOpaque(true);
        getContentPane().add(lblSH1);
        lblSH1.setBounds(40, 470, 60, 60);

        lblSH2.setBackground(new java.awt.Color(255, 255, 255));
        lblSH2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH2.setOpaque(true);
        getContentPane().add(lblSH2);
        lblSH2.setBounds(100, 470, 60, 60);

        lblSH3.setBackground(new java.awt.Color(255, 255, 255));
        lblSH3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH3.setOpaque(true);
        getContentPane().add(lblSH3);
        lblSH3.setBounds(160, 470, 60, 60);

        lblSH4.setBackground(new java.awt.Color(255, 255, 255));
        lblSH4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH4.setOpaque(true);
        getContentPane().add(lblSH4);
        lblSH4.setBounds(220, 470, 60, 60);

        lblSH5.setBackground(new java.awt.Color(255, 255, 255));
        lblSH5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH5.setOpaque(true);
        getContentPane().add(lblSH5);
        lblSH5.setBounds(280, 470, 60, 60);

        lblSH6.setBackground(new java.awt.Color(255, 255, 255));
        lblSH6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH6.setOpaque(true);
        getContentPane().add(lblSH6);
        lblSH6.setBounds(340, 470, 60, 60);

        lblSH7.setBackground(new java.awt.Color(255, 255, 255));
        lblSH7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH7.setOpaque(true);
        getContentPane().add(lblSH7);
        lblSH7.setBounds(400, 470, 60, 60);

        lblSH8.setBackground(new java.awt.Color(255, 255, 255));
        lblSH8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH8.setOpaque(true);
        getContentPane().add(lblSH8);
        lblSH8.setBounds(460, 470, 60, 60);

        lblSH9.setBackground(new java.awt.Color(255, 255, 255));
        lblSH9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH9.setOpaque(true);
        getContentPane().add(lblSH9);
        lblSH9.setBounds(520, 470, 60, 60);

        lblSH10.setBackground(new java.awt.Color(255, 255, 255));
        lblSH10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSH10.setOpaque(true);
        getContentPane().add(lblSH10);
        lblSH10.setBounds(580, 470, 60, 60);

        lblSI1.setBackground(new java.awt.Color(255, 255, 255));
        lblSI1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI1.setOpaque(true);
        getContentPane().add(lblSI1);
        lblSI1.setBounds(40, 530, 60, 60);

        lblSI2.setBackground(new java.awt.Color(255, 255, 255));
        lblSI2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI2.setOpaque(true);
        getContentPane().add(lblSI2);
        lblSI2.setBounds(100, 530, 60, 60);

        lblSI3.setBackground(new java.awt.Color(255, 255, 255));
        lblSI3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI3.setOpaque(true);
        getContentPane().add(lblSI3);
        lblSI3.setBounds(160, 530, 60, 60);

        lblSI4.setBackground(new java.awt.Color(255, 255, 255));
        lblSI4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI4.setOpaque(true);
        getContentPane().add(lblSI4);
        lblSI4.setBounds(220, 530, 60, 60);

        lblSI5.setBackground(new java.awt.Color(255, 255, 255));
        lblSI5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI5.setOpaque(true);
        getContentPane().add(lblSI5);
        lblSI5.setBounds(280, 530, 60, 60);

        lblSI6.setBackground(new java.awt.Color(255, 255, 255));
        lblSI6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI6.setOpaque(true);
        getContentPane().add(lblSI6);
        lblSI6.setBounds(340, 530, 60, 60);

        lblSI7.setBackground(new java.awt.Color(255, 255, 255));
        lblSI7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI7.setOpaque(true);
        getContentPane().add(lblSI7);
        lblSI7.setBounds(400, 530, 60, 60);

        lblSI8.setBackground(new java.awt.Color(255, 255, 255));
        lblSI8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI8.setOpaque(true);
        getContentPane().add(lblSI8);
        lblSI8.setBounds(460, 530, 60, 60);

        lblSI9.setBackground(new java.awt.Color(255, 255, 255));
        lblSI9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSI9.setOpaque(true);
        getContentPane().add(lblSI9);
        lblSI9.setBounds(520, 530, 60, 60);

        lblIS10.setBackground(new java.awt.Color(255, 255, 255));
        lblIS10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIS10.setOpaque(true);
        getContentPane().add(lblIS10);
        lblIS10.setBounds(580, 530, 60, 60);

        lblSJ1.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ1.setOpaque(true);
        getContentPane().add(lblSJ1);
        lblSJ1.setBounds(40, 590, 60, 60);

        lblSJ2.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ2.setOpaque(true);
        getContentPane().add(lblSJ2);
        lblSJ2.setBounds(100, 590, 60, 60);

        lblSJ3.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ3.setOpaque(true);
        getContentPane().add(lblSJ3);
        lblSJ3.setBounds(160, 590, 60, 60);

        lblSJ4.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ4.setOpaque(true);
        getContentPane().add(lblSJ4);
        lblSJ4.setBounds(220, 590, 60, 60);

        lblSJ5.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ5.setOpaque(true);
        getContentPane().add(lblSJ5);
        lblSJ5.setBounds(280, 590, 60, 60);

        lblSJ6.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ6.setOpaque(true);
        getContentPane().add(lblSJ6);
        lblSJ6.setBounds(340, 590, 60, 60);

        lblSJ7.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ7.setOpaque(true);
        getContentPane().add(lblSJ7);
        lblSJ7.setBounds(400, 590, 60, 60);

        lblSJ8.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ8.setOpaque(true);
        getContentPane().add(lblSJ8);
        lblSJ8.setBounds(460, 590, 60, 60);

        lblSJ9.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ9.setOpaque(true);
        getContentPane().add(lblSJ9);
        lblSJ9.setBounds(520, 590, 60, 60);

        lblSJ10.setBackground(new java.awt.Color(255, 255, 255));
        lblSJ10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSJ10.setOpaque(true);
        getContentPane().add(lblSJ10);
        lblSJ10.setBounds(580, 590, 60, 60);

        jLabel1.setText("J");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 610, 20, 16);

        lblBoardSideA.setText("A");
        getContentPane().add(lblBoardSideA);
        lblBoardSideA.setBounds(20, 70, 20, 16);

        lblBoardSideB.setText("B");
        getContentPane().add(lblBoardSideB);
        lblBoardSideB.setBounds(20, 130, 20, 16);

        lblBoardSideC.setText("C");
        getContentPane().add(lblBoardSideC);
        lblBoardSideC.setBounds(20, 190, 20, 16);

        lblBoardSideD.setText("D");
        getContentPane().add(lblBoardSideD);
        lblBoardSideD.setBounds(20, 250, 20, 16);

        lblBoardSideE.setText("E");
        getContentPane().add(lblBoardSideE);
        lblBoardSideE.setBounds(20, 310, 20, 16);

        lblBoardSideF.setText("F");
        getContentPane().add(lblBoardSideF);
        lblBoardSideF.setBounds(20, 370, 20, 16);

        jLabel10.setText("G");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 430, 20, 16);

        jLabel11.setText("H");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 490, 20, 16);

        jLabel12.setText("I");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 550, 20, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA10;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblA6;
    private javax.swing.JLabel lblA7;
    private javax.swing.JLabel lblA8;
    private javax.swing.JLabel lblA9;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB10;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblB6;
    private javax.swing.JLabel lblB7;
    private javax.swing.JLabel lblB8;
    private javax.swing.JLabel lblB9;
    private javax.swing.JLabel lblBoardSideA;
    private javax.swing.JLabel lblBoardSideB;
    private javax.swing.JLabel lblBoardSideC;
    private javax.swing.JLabel lblBoardSideD;
    private javax.swing.JLabel lblBoardSideE;
    private javax.swing.JLabel lblBoardSideF;
    private javax.swing.JLabel lblBoardTopNumbers;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC10;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblC9;
    private javax.swing.JLabel lblIS10;
    private javax.swing.JLabel lblSD1;
    private javax.swing.JLabel lblSD2;
    private javax.swing.JLabel lblSD3;
    private javax.swing.JLabel lblSE1;
    private javax.swing.JLabel lblSE10;
    private javax.swing.JLabel lblSE2;
    private javax.swing.JLabel lblSE3;
    private javax.swing.JLabel lblSE4;
    private javax.swing.JLabel lblSE5;
    private javax.swing.JLabel lblSE6;
    private javax.swing.JLabel lblSE7;
    private javax.swing.JLabel lblSE8;
    private javax.swing.JLabel lblSE9;
    private javax.swing.JLabel lblSF1;
    private javax.swing.JLabel lblSF10;
    private javax.swing.JLabel lblSF2;
    private javax.swing.JLabel lblSF3;
    private javax.swing.JLabel lblSF4;
    private javax.swing.JLabel lblSF5;
    private javax.swing.JLabel lblSF6;
    private javax.swing.JLabel lblSF7;
    private javax.swing.JLabel lblSF8;
    private javax.swing.JLabel lblSF9;
    private javax.swing.JLabel lblSG1;
    private javax.swing.JLabel lblSG10;
    private javax.swing.JLabel lblSG2;
    private javax.swing.JLabel lblSG3;
    private javax.swing.JLabel lblSG4;
    private javax.swing.JLabel lblSG5;
    private javax.swing.JLabel lblSG6;
    private javax.swing.JLabel lblSG7;
    private javax.swing.JLabel lblSG8;
    private javax.swing.JLabel lblSG9;
    private javax.swing.JLabel lblSH1;
    private javax.swing.JLabel lblSH10;
    private javax.swing.JLabel lblSH2;
    private javax.swing.JLabel lblSH3;
    private javax.swing.JLabel lblSH4;
    private javax.swing.JLabel lblSH5;
    private javax.swing.JLabel lblSH6;
    private javax.swing.JLabel lblSH7;
    private javax.swing.JLabel lblSH8;
    private javax.swing.JLabel lblSH9;
    private javax.swing.JLabel lblSI1;
    private javax.swing.JLabel lblSI2;
    private javax.swing.JLabel lblSI3;
    private javax.swing.JLabel lblSI4;
    private javax.swing.JLabel lblSI5;
    private javax.swing.JLabel lblSI6;
    private javax.swing.JLabel lblSI7;
    private javax.swing.JLabel lblSI8;
    private javax.swing.JLabel lblSI9;
    private javax.swing.JLabel lblSJ1;
    private javax.swing.JLabel lblSJ10;
    private javax.swing.JLabel lblSJ2;
    private javax.swing.JLabel lblSJ3;
    private javax.swing.JLabel lblSJ4;
    private javax.swing.JLabel lblSJ5;
    private javax.swing.JLabel lblSJ6;
    private javax.swing.JLabel lblSJ7;
    private javax.swing.JLabel lblSJ8;
    private javax.swing.JLabel lblSJ9;
    // End of variables declaration//GEN-END:variables
}
